apiVersion: apps/v1
kind: Deployment

metadata:
  name: mongodb-admin-deployment

spec:
  replicas: 1   

  selector:     
    matchLabels:
      app: mongo_admin

  template:    
    metadata:
      labels:
        app: mongo_admin  

    spec:
      containers:
      - name: mongodb-admin-container
        image: mongo
        ports:
        - containerPort: 27017

        env:
        - name: MONGO_INITDB_ROOT_USERNAME  
          valueFrom:
            secretKeyRef:
              name: mongo-admin-creds  
              key: username  

        - name: MONGO_INITDB_ROOT_PASSWORD  
          valueFrom:
            secretKeyRef:
              name: mongo-admin-creds  
              key: password 

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: mongo-express-deployment

spec:
  replicas: 1   

  selector:     
    matchLabels:
      app: mongo_express

  template:     
    metadata:
      labels:
        app: mongo_express  

    spec:
      containers:
      - name: mongo-express-container
        image: mongo-express
        ports:
        - containerPort: 8081  
        imagePullPolicy: Always

        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME  
          valueFrom:
            configMapKeyRef:
              name: mongo-express-configmap  
              key: admin_user  

        - name: ME_CONFIG_MONGODB_ADMINPASSWORD  
          valueFrom:
            configMapKeyRef:
              name: mongo-express-configmap  
              key: admin_pass

        - name: ME_CONFIG_MONGODB_SERVER  
          valueFrom:
            configMapKeyRef:
              name: mongo-express-configmap  
              key: mongo_server_url
---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-app-deployment

spec:
  replicas: 1   

  selector:     
    matchLabels:
      app: flask_app

  template:     
    metadata:
      labels:
        app: flask_app  

    spec:
      containers:
      - name: flask-app-container
        image: gokul007x/kub-flask-app   
        imagePullPolicy: Always  
        ports:
        - containerPort: 5001   
