apiVersion: v1
kind: Service

metadata:
  name: mongodb-admin-service

spec:
  selector:
    app: mongo_admin  

  type: ClusterIP   

  ports:
    - protocol: 'TCP'
      port: 27017   
      targetPort: 27017   


apiVersion: v1
kind: Service

metadata:
  name: mongo-express-service

spec:
  selector:
    app: mongo_express  

  ports:
    - protocol: 'TCP'
      port: 5555     
      targetPort: 8081   
      nodePort: 32510

  type: LoadBalancer
---

apiVersion: v1
kind: Service

metadata:
  name: flask-app-service

spec:
  selector:
    app: flask_app  

  ports:
    - protocol: 'TCP'
      port: 4444     
      targetPort: 5001   
      nodePort: 32500

  type: LoadBalancer
